import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { Crimson_Pro, Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import logo from './../components/images/logo-no-background.png';
import FPDisplayCard from '@/components/FPDisplayCard';
import reward from './../components/images/icons8-money-bag-50.png';
import happy from './../components/images/icons8-happy-64.png';
import dinner from './../components/images/icons8-dinner-50.png';
import pizza from './../components/images/icons8-salami-pizza-50.png';
import wine from './../components/images/icons8-food-and-wine-50.png';
import Button from './../components/Button';
import SignIn from './../components/SignIn';
import Link from 'next/link';
const crimson = Crimson_Pro({ subsets: ['latin'] });

export default function Home() {
  const [signIn, setSignIn] = useState(false);
  const [signUp, setSignUp] = useState(false);

  return (
    <>
      <Head>
        <title>Worst Restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`flexCent ${crimson.className} ${styles.main}`}>
        <div className={`flexCent ${styles.restaurantLink}`}>
          <Link href="/restaurants">
            <h1>
              See<br></br> Our<br></br> Restaurants!
            </h1>
          </Link>
        </div>
        <div className={styles.container}>
          <div className={styles.leftHalf}>
            <section className={`flexCent ${styles.logoSection}`}>
              <Image src={logo} width={600} />
            </section>
            <section className={`flexCent ${styles.cardSection}`}>
              <FPDisplayCard
                displayImage={dinner}
                header={'Support Local'}
                tagline={
                  'Help keep bad restaurants and the local economy afloat.'
                }
              />
              <FPDisplayCard
                displayImage={happy}
                header={'More For Less'}
                tagline={
                  'Or maybe more... We did say there would be service fees.'
                }
              />
              <FPDisplayCard
                displayImage={reward}
                header={'Get Rewarded'}
                tagline={
                  "Who doesn't love some good old fashioned negative reinforcement?"
                }
              />
            </section>
            <section className={`flexCent ${styles.buttonSection}`}>
              <Button margin={40} clickFunc={setSignIn} icon={pizza} text="sign up" />
              <Button margin={40} clickFunc={setSignUp} icon={wine} text="sign in" />
            </section>
          </div>
          <div className={`flexCent ${styles.rightHalf}`}>
            {signIn && <SignIn />}
          </div>
        </div>
      </main>
    </>
  );
}
